cache:
  key: "$CI_JOB_NAME"
  paths:
    - .m2/repository
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

deploy:
  only:
    - main
  image: jelastic/maven:3.9.5-openjdk-21
  before_script:
    - chmod 770 ./ci/setup-mvn-proxy.sh
    - ./ci/setup-mvn-proxy.sh
    - echo "$CI_SSH_KEY" > /tmp/deploy_key
    - chmod 600 /tmp/deploy_key
  script:
    - cd ./$PROJECT_FOLDER_NAME
    - mvn clean package
    - scp -o StrictHostKeyChecking=no -i /tmp/deploy_key /builds/p1907037/mif13/$PROJECT_FOLDER_NAME/target/$SOURCE_WAR_NAME.war gitlabci@192.168.75.23:/opt/tomcat/webapps/$DESTINATION_WAR_NAME.war
  after_script:
    - rm -f /tmp/deploy_key

deploy_api:
  only:
    - main
  image: node:21.3.0-alpine3.18
  before_script:
    - apk add --no-cache openssh-client
    - chmod 770 ./ci/setup-mvn-proxy.sh
    - ./ci/setup-mvn-proxy.sh
    - echo "$CI_SSH_KEY" > /tmp/deploy_key
    - chmod 600 /tmp/deploy_key
  script:
    - cd ./api
    - npm i
    - npm run build
    - tar cvf build.tar.gz node_modules dist > /dev/null 2>&1
    - scp -o StrictHostKeyChecking=no -i /tmp/deploy_key build.tar.gz gitlabci@192.168.75.23:/home/gitlabci/api/build.tar.gz
    - ssh -o StrictHostKeyChecking=no -i /tmp/deploy_key gitlabci@192.168.75.23 "cd api && tar xvf build.tar.gz > /dev/null 2>&1"
    - ssh -o StrictHostKeyChecking=no -i /tmp/deploy_key gitlabci@192.168.75.23 "cd api && pm2 delete api || true"
    - ssh -o StrictHostKeyChecking=no -i /tmp/deploy_key gitlabci@192.168.75.23 "cd api && pm2 start dist/index.js --name 'api'"
    - cd ../admin
    - npm i
    - npm run build
    - tar cvf build.tar.gz node_modules dist > /dev/null 2>&1
    - scp -o StrictHostKeyChecking=no -i /tmp/deploy_key build.tar.gz gitlabci@192.168.75.23:/home/gitlabci/admin/build.tar.gz
    - ssh -o StrictHostKeyChecking=no -i /tmp/deploy_key gitlabci@192.168.75.23 'sudo mv /home/gitlabci/admin/build.tar.gz /usr/share/nginx/secret/'
    - ssh -o StrictHostKeyChecking=no -i /tmp/deploy_key gitlabci@192.168.75.23 "cd /usr/share/nginx/secret && sudo tar xvf build.tar.gz > /dev/null 2>&1"
  after_script:
    - rm -f /tmp/deploy_key

deploy_tp:
  stage: deploy
  image: jelastic/maven:3.9.5-openjdk-21
  before_script:
    - chmod 770 ./ci/setup-mvn-proxy.sh
    - ./ci/setup-mvn-proxy.sh
    - echo "$CI_SSH_KEY" > /tmp/deploy_key
    - chmod 600 /tmp/deploy_key
  script:
    - cd ./$PROJECT_FOLDER_NAME
    - mvn clean package
    - ssh -o StrictHostKeyChecking=no -i /tmp/deploy_key gitlabci@192.168.75.23 "mkdir -p /opt/tomcat/webapps/$CI_COMMIT_REF_NAME"
    - scp -o StrictHostKeyChecking=no -i /tmp/deploy_key /builds/p1907037/mif13/$PROJECT_FOLDER_NAME/target/$SOURCE_WAR_NAME.war gitlabci@192.168.75.23:/opt/tomcat/webapps/$CI_COMMIT_REF_NAME.war
  after_script:
    - rm -f /tmp/deploy_key
  only:
    - /^TP[0-9]+$/
  except:
    - main
